// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADi7jG-XWwghBd9TAJJ2a8mVARnFQzC0M',
    appId: '1:269432577885:web:83f2e62113c02c5f7692b4',
    messagingSenderId: '269432577885',
    projectId: 'taazetest-a5147',
    authDomain: 'taazetest-a5147.firebaseapp.com',
    storageBucket: 'taazetest-a5147.appspot.com',
    measurementId: 'G-29K3FZNFP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1OF-k_L7BPipzouz_rDdY5BbtuytZlo0',
    appId: '1:269432577885:android:4719a61f832058d67692b4',
    messagingSenderId: '269432577885',
    projectId: 'taazetest-a5147',
    storageBucket: 'taazetest-a5147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuUn1VMmJDj4gMWx8l29C3RG1W9JfNfU',
    appId: '1:269432577885:ios:bc87180a199d9cd87692b4',
    messagingSenderId: '269432577885',
    projectId: 'taazetest-a5147',
    storageBucket: 'taazetest-a5147.appspot.com',
    iosClientId:
        '269432577885-p0q5j0mllf75d16lvme2k52pi3apb2dr.apps.googleusercontent.com',
    iosBundleId: 'testingdomain.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuUn1VMmJDj4gMWx8l29C3RG1W9JfNfU',
    appId: '1:269432577885:ios:bc87180a199d9cd87692b4',
    messagingSenderId: '269432577885',
    projectId: 'taazetest-a5147',
    storageBucket: 'taazetest-a5147.appspot.com',
    iosClientId:
        '269432577885-p0q5j0mllf75d16lvme2k52pi3apb2dr.apps.googleusercontent.com',
    iosBundleId: 'testingdomain.myNotes',
  );
}
